### ISSUE TITLE
pkc_flush may block forever

### ISSUE THREAD

**Issue by guillerodriguez** [pagekite/libpagekite#38]
There are cases where [`pkc_flush`](https://github.com/pagekite/libpagekite/blob/c9e41f7c5ed4c20d8f52877492b3d13597062fcd/libpagekite/pkconn.c#L389) may block forever. Here is one such scenario:

 - [`pk_connect_ai`](https://github.com/pagekite/libpagekite/blob/c9e41f7c5ed4c20d8f52877492b3d13597062fcd/libpagekite/pkproto.c#L582) is called.
 - `pk_connect_ai` calls `pkc_start_ssl`, which in turn calls [`pkc_do_handshake`](https://github.com/pagekite/libpagekite/blob/c9e41f7c5ed4c20d8f52877492b3d13597062fcd/libpagekite/pkconn.c#L149). Let's assume `pkc_do_handshake` does not fail, but it does not complete the handshake immediately, and sets `SSL_ERROR_WANT_READ` or `SSL_ERROR_WANT_WRITE`.
 - Because the TLS handshake is not completed, subsequent calls to `pkc_write` or `pkc_read` will end up calling `pkc_do_handshake` again. Let's assume that [in the next `pkc_write` call](https://github.com/pagekite/libpagekite/blob/c9e41f7c5ed4c20d8f52877492b3d13597062fcd/libpagekite/pkproto.c#L611) there is a handshake error and `pkc_do_handshake`sets `CONN_STATUS_BROKEN`.
 - [This call to `pkc_flush`](https://github.com/pagekite/libpagekite/blob/c9e41f7c5ed4c20d8f52877492b3d13597062fcd/libpagekite/pkproto.c#L630) will now block forever in a busy loop.

(Note: Before the recent changes, this busy loop would break when the tunnel is disconnected. After [this commit](https://github.com/pagekite/libpagekite/commit/7c4f4a906070b22f28bbdd125ab8f4456080c8e0) tunnels are not disconnected anymore if they are in the middle of a change, meaning this busy loop never completes.)

**Comment by BjarniRunar** [comment]
Hmm, I think this depends on whether OpenSSL sets `errno`. I don't know if it does, but my guess is no.

Rationale: `pkc_flush` will invoke `pkc_raw_write`, which in turn invokes `SSL_write`, which should return a negative value which propagates back up the call stack unless we know how to handle the error, in which case we return 0. The `pkc_flush()` loop will abort if `errno` is nonzero and not `EINTR` - so yes, if OpenSSL leaves `errno` as zero we could indeed have an infinite loop here.

So, rather than wonder and guess, let's put on a belt and suspenders:

   1. let's explicitly set `errno` to something appropriate in the places where we are processing the results of `SSL_get_error` and get an unrecoverable error. ECONNRESET or EIO seem appropriate. 
   2. let's put an upper bound on how often pkc_flush() can loop before giving up

Sound good?

**Comment by guillerodriguez** [comment]
Looking at [this description of `SSL_get_error`](https://wiki.openssl.org/index.php/Manual:SSL_get_error(3)), I'd say that OpenSSL may or may not set `errno`, depending on the type of error (see specifically the description of `SSL_ERROR_SYSCALL`).

Yes, your suggested approach sounds good.

Also it may be a good idea to check that all current users of `pkc_flush` are prepared to handle the case of `pkc_flush` failing.

**Comment by BjarniRunar** [comment]
Agreed. For the most part, return values from pkc_flush and pkc_write are ignored and the app relies on the status flags being set appropriately when there's a problem.
